# Generated by Django 2.0 on 2018-04-04 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classifer',
            old_name='input',
            new_name='inputtext',
        ),
    ]
