# Generated by Django 2.0 on 2018-04-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180404_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifer',
            name='times',
            field=models.DateTimeField(),
        ),
    ]
